// frontend-old/src/App.tsx
import { useState, useEffect } from 'react';
import './App.css';
import type { User, CreateUserCommand } from './types.ts';
import { userService } from './userService.ts';

function App() {
  const [users, setUsers] = useState<User[]>([]);
  const [formData, setFormData] = useState<CreateUserCommand>({ name: '', email: '' });
  const [editingId, setEditingId] = useState<string | null>(null);
  const [notification, setNotification] = useState<{ message: string; type: 'success' | 'error' } | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      const data = await userService.getAll();
      setUsers(data);
    } catch (err) {
      showNotification('Failed to load users', 'error');
    }
  };

  const showNotification = (message: string, type: 'success' | 'error') => {
    setNotification({ message, type });
    setTimeout(() => setNotification(null), 3000);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      if (editingId) {
        await userService.update(editingId, { ...formData, id: editingId });
        showNotification('User updated successfully!', 'success');
      } else {
        await userService.create(formData);
        showNotification('User registered successfully!', 'success');
      }
      setFormData({ name: '', email: '' });
      setEditingId(null);
      fetchUsers();
    } catch (err: any) {
      showNotification(err.message, 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleEdit = (user: User) => {
    setEditingId(user.id);
    setFormData({ name: user.name, email: user.email });
  };

  const cancelEdit = () => {
    setEditingId(null);
    setFormData({ name: '', email: '' });
  };

  return (
    <div className="App">
      <header style={{ marginBottom: '2rem', textAlign: 'center' }}>
        <h1 style={{ fontSize: '2rem', color: 'var(--primary)' }}>User Manager</h1>
        <p style={{ color: 'var(--text-muted)' }}>DDD + CQRS + Spring Boot + React</p>
      </header>

      <main className="container">
        {/* Registration/Edit Form */}
        <section className="card">
          <h2>{editingId ? 'Edit User' : 'Register User'}</h2>
          <form onSubmit={handleSubmit}>
            <div className="form-group">
              <label>Full Name</label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder="John Doe"
                required
              />
            </div>
            <div className="form-group">
              <label>Email Address</label>
              <input
                type="email"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                placeholder="john@example.com"
                required
              />
            </div>
            <button type="submit" className="btn-primary" disabled={loading}>
              {loading ? 'Processing...' : editingId ? 'Update User' : 'Register User'}
            </button>
            {editingId && (
              <button type="button" onClick={cancelEdit} className="btn-secondary">
                Cancel
              </button>
            )}
          </form>
        </section>

        {/* User List */}
        <section className="card">
          <h2>User List</h2>
          {users.length === 0 ? (
            <p style={{ textAlign: 'center', color: 'var(--text-muted)' }}>No users found.</p>
          ) : (
            <ul className="user-list">
              {users.map((user) => (
                <li key={user.id} className="user-item">
                  <div className="user-info">
                    <span className="name">{user.name}</span>
                    <span className="email">{user.email}</span>
                  </div>
                  <div className="actions">
                    <button onClick={() => handleEdit(user)} className="btn-edit">
                      Edit
                    </button>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </section>
      </main>

      {/* Toast Notifications */}
      {notification && (
        <div className={`notification ${notification.type}`}>
          {notification.message}
        </div>
      )}
    </div>
  );
}

export default App;

// frontend/src/app/app.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { UserService } from './services/user.service';
import { User, CreateUserCommand } from './models/user.model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly userService = inject(UserService);

  users: User[] = [];
  userForm: FormGroup;
  editingId: string | null = null;
  loading = false;
  notification: { message: string; type: 'success' | 'error' } | null = null;

  constructor() {
    this.userForm = this.fb.group({
      name: ['', [Validators.required]],
      email: ['', [Validators.required, Validators.email]]
    });
  }

  ngOnInit(): void {
    this.fetchUsers();
  }

  fetchUsers(): void {
    this.userService.getAll().subscribe({
      next: (data) => this.users = data,
      error: () => this.showNotification('Failed to load users', 'error')
    });
  }

  showNotification(message: string, type: 'success' | 'error'): void {
    this.notification = { message, type };
    setTimeout(() => this.notification = null, 3000);
  }

  handleSubmit(): void {
    if (this.userForm.invalid) return;

    this.loading = true;
    const formData = this.userForm.value;

    if (this.editingId) {
      this.userService.update(this.editingId, { ...formData, id: this.editingId }).subscribe({
        next: () => {
          this.showNotification('User updated successfully!', 'success');
          this.resetForm();
          this.fetchUsers();
        },
        error: (err) => {
          this.showNotification(err.error?.error || 'Failed to update user', 'error');
          this.loading = false;
        }
      });
    } else {
      this.userService.create(formData).subscribe({
        next: () => {
          this.showNotification('User registered successfully!', 'success');
          this.resetForm();
          this.fetchUsers();
        },
        error: (err) => {
          this.showNotification(err.error?.error || 'Failed to create user', 'error');
          this.loading = false;
        }
      });
    }
  }

  handleEdit(user: User): void {
    this.editingId = user.id;
    this.userForm.patchValue({
      name: user.name,
      email: user.email
    });
  }

  cancelEdit(): void {
    this.resetForm();
  }

  private resetForm(): void {
    this.editingId = null;
    this.userForm.reset();
    this.loading = false;
  }
  deleteUser(id: string): void {
       if (confirm('Tem certeza que deseja excluir este usuário?')) {
           this.userService.delete(id).subscribe({
               next: () => {
                 this.showNotification('Usuário excluído!', 'success');
                 this.fetchUsers();
               },
               error: () => this.showNotification('Erro ao excluir usuário', 'error')
           });
         }
     }
}

<div class="App">
  <header style="margin-bottom: 2rem; text-align: center;">
    <h1 style="font-size: 2rem; color: var(--primary);">User Manager</h1>
    <p style="color: var(--text-muted);">DDD + CQRS + Spring Boot + Angular 18</p>
  </header>

  <main class="container">
    <!-- Registration/Edit Form -->
    <section class="card">
      <h2>{{ editingId ? 'Edit User' : 'Register User' }}</h2>
       <form [formGroup]="userForm" (ngSubmit)="handleSubmit()">
         <div class="form-group">
           <label>Full Name</label>
           <input
             type="text"
             formControlName="name"
             placeholder="John Doe"
           />
           <!-- MENSAGEM DE ERRO DO NOME -->
           @if (userForm.get('name')?.invalid && userForm.get('name')?.touched) {
             <small style="color: var(--error);">O nome é obrigatório.</small>
           }
         </div>
         <div class="form-group">
           <label>Email Address</label>
           <input
             type="email"
             formControlName="email"
             placeholder="john@example.com"
           />
           <!-- MENSAGEM DE ERRO DO E-MAIL -->
           @if (userForm.get('email')?.invalid && userForm.get('email')?.touched) {
             <small style="color: var(--error);">
                 @if (userForm.get('email')?.errors?.['required']) {
                   O e-mail é obrigatório.
                   } @else {
                   Digite um e-mail válido (ex: nome@email.com).
                   }
               </small>
           }
         </div>
         <button type="submit" class="btn-primary" [disabled]="loading || userForm.invalid">
           {{ loading ? 'Processing...' : (editingId ? 'Update User' : 'Register User') }}
         </button>
        @if (editingId) {
          <button type="button" (click)="cancelEdit()" class="btn-secondary">
            Cancel
          </button>
        }
      </form>
    </section>

    <!-- User List -->
    <section class="card">
      <h2>User List</h2>
      @if (users.length === 0) {
        <p style="text-align: center; color: var(--text-muted);">No users found.</p>
      } @else {
        <ul class="user-list">
          @for (user of users; track user.id) {
            <li class="user-item">
              <div class="user-info">
                <span class="name">{{ user.name }}</span>
                <span class="email">{{ user.email }}</span>
              </div>
              <div class="actions">
                <button (click)="handleEdit(user)" class="btn-edit">Editar</button>
                <button (click)="deleteUser(user.id)" class="btn-delete" style="background: var(--error); color: white; margin-left: 5px;">
                  Excluir
                </button>
              </div>
            </li>
          }
        </ul>
      }
    </section>
  </main>

  <!-- Toast Notifications -->
  @if (notification) {
    <div class="notification" [ngClass]="notification.type">
      {{ notification.message }}
    </div>
  }
</div>
